export const MainPageContentEN = {
    nameLabel: 'Andreas N. Drandakis',
    progessionLabel: 'Lawyer | Specializing in Civil & Corporate Law',
    bioHeaderLabel: 'Welcome,',
    bioBodyLabel: 'With solid expertise and professional experience, our law office offers high-quality legal services across a broad range of legal fields. With excellent command of German and English, guided by our clients’ best interests and a strong sense of professionalism, our goal is to protect your rights by providing effective, tailored solutions for each individual case.',
    servicesLabel: 'Services',
    servicesDetailsLabel: 'Click on a bubble to see more details',
    
    serviceLabel1: 'Civil Law',
    serviceLabel2: 'Commercial-Corporate Law',
    serviceLabel3: 'Administrative Law',
    serviceLabel4: 'Criminal Law',
    serviceLabel5: 'Labor Law',
    serviceLabel6: 'Foreigners Law',
    serviceLabel7: 'Certified Document Translations',
    
    serviceBody1: 'Real Estate-Land Registry, Leases, Loans, Family Law, Inheritance Law, Monetary Claims, Associations',
    serviceBody2: 'Company formation-merger-division-transfer, Disputes between partners or shareholders, Company dissolution-bankruptcy, Distribution and commercial agency agreements, Negotiable instruments',
    serviceBody3: 'Disputes with the Public Sector, Objections and appeals, Lawsuits for monetary claims against the Public Sector, Tax disputes',
    serviceBody4: 'Representation before criminal courts, Drafting of complaints / briefs / petitions to prosecutorial and judicial authorities',
    serviceBody5: 'Disputes arising from employment contracts, Disputes with social security funds',
    serviceBody6: 'Residence permits, Greek citizenship',
    serviceBody7: '',

    contactLabel: 'Contact',
    contactMeLabel: 'Find us',
    contactNameLabel: 'Name',
    contactSurnNameLabel: 'Surname',
    contactNamePlaceholder: 'John',
    contactSurnNamePlaceholder: 'Doe',
    contactEmailLabel: 'Email',
    contactEmailPlaceholder: 'johndoe@gmail.com',
    contactMessageLabel: 'Message',
    contactMessagePlaceholder: 'I contant you, for ....',
    contactSendLabel: 'Αποστολή Μηνύματος',
    contactSendingLabel: 'Sending...',
}

export const MainPageContentGR = {
    nameLabel: 'Ανδρέας Ν. Δρανδάκης',
    progessionLabel: 'Δικηγόρος | Ειδικός στο Αστικό &amp; Εταιρικό Δίκαιο',
    bioHeaderLabel: 'Καλώς ήρθατε,',
    bioBodyLabel: 'Με άρτια κατάρτιση και επαγγελματική εμπειρία, το γραφείο μας παρέχει νομικές υπηρεσίες υψηλού επιπέδου σε ευρύ φάσμα του δικαίου. Πάντα με γνώμονα το συμφέρον του πελάτη και επαγγελματισμό, στόχος μας είναι η προάσπιση των δικαιωμάτων σας, παρέχοντας αποτελεσματικές λύσεις προσαρμοσμένες στις ανάγκες κάθε υπόθεσης.',
    servicesLabel: 'Υπηρεσίες',
    servicesDetailsLabel: 'Κάντε κλικ σε μια φυσαλίδα για να δείτε περισσότερες λεπτομέρειες',
    
    serviceLabel1: 'Αστικό Δίκαιο',
    serviceLabel2: 'Εμπορικό-Εταιρικό Δίκαιο',
    serviceLabel3: 'Διοικητικό Δίκαιο',
    serviceLabel4: 'Ποινικό Δίκαιο',
    serviceLabel5: 'Εργατικό Δίκαιο',
    serviceLabel6: 'Δίκαιο Αλλοδαπών',
    serviceLabel7: 'Επικυρωμένες μεταφράσεις εγγράφων',
    
    serviceBody1: 'Ακίνητα-Κτηματολόγιο, Μισθώσεις, Δάνεια, Οικογενειακά, Κληρονομικά, Σωματεία, Διεκδίκηση χρηματικών απαιτήσεων',
    serviceBody2: 'Σύσταση-συγχώνευση-διάσπαση-μεταβίβαση εταιριών, Διαφορές μεταξύ εταίρων ή μετόχων, Λύση-Πτώχευση εταιρίας, Αξιόγραφα, Συμβάσεις διανομής-εμπορικής αντιπροσωπείας',
    serviceBody3: 'Διαφορές με το Δημόσιο, Ενστάσεις και προσφυγές, Αγωγές για διεκδίκηση χρηματικών απαιτήσεων από το Δημόσιο, Φορολογικές διαφορές',
    serviceBody4: 'Εκπροσώπηση ενώπιον ποινικών δικαστηρίων, Σύνταξη μηνύσεων / υπομνημάτων / αιτήσεων προς εισαγγελικές και δικαστικές αρχές',
    serviceBody5: 'Διαφορές από συβάσεις εργασίας, Διαφορές με ασφαλιστικά ταμεία',
    serviceBody6: 'Άδειες διαμονής, Ελληνική ιθαγένεια',
    serviceBody7: '',

    contactLabel: 'Επικοινωνία',
    contactMeLabel: 'Βρείτε μας',
    contactNameLabel: 'Όνομα',
    contactSurnNameLabel: 'Επώνυμο',
    contactNamePlaceholder: 'Γιάννης',
    contactSurnNamePlaceholder: 'Γιαννάκης',
    contactEmailLabel: 'Ηλεκτρονικό Ταχυδρομείο',
    contactEmailPlaceholder: 'johndoe@gmail.com',
    contactMessageLabel: 'Μήνυμα',
    contactMessagePlaceholder: 'Επικοινωνώ μαζί σας, για ....',
    contactSendLabel: 'Αποστολή Μηνύματος',
    contactSendingLabel: 'Αποστολή...',
}