export const MainPageContentEN = {
    nameLabel: 'Andreas N. Drandakis',
    progessionLabel: 'Licensed Attorney | Specializing in Corporate & Civil Law',
    bioHeaderLabel: 'Hello,',
    bioBodyLabel: 'I Adnreaw and am a licensed attorney with over 10 years of experience in corporate and civil law. My expertise includes corporate governance, contract law, and dispute resolution. I am committed to providing my clients with the highest level of legal service and support.',
    servicesLabel: 'Services',
    serviceLabel1: 'Corporate Law',
    serviceLabel2: 'Civil Law',
    serviceLabel3: 'Legal Advisory Services',
    serviceLabel4: 'Contract Drafting and Review',
    serviceBody1: 'Corporate law governs the formation, operation, and dissolution of companies. It covers areas such as mergers and acquisitions, compliance, corporate governance, and shareholder rights, ensuring that businesses operate within the legal framework and maintain ethical standards.',
    serviceBody2: 'Civil law regulates the relationships between private individuals and/or legal entities, covering issues such as contractual disputes, property rights, and tort claims. Its aim is to resolve disputes fairly through negotiation, settlement, or litigation.',
    serviceBody3: 'Legal advisory services provide clients with expert guidance on a variety of legal matters, helping them navigate complex regulations and make informed decisions. These services include risk assessment, compliance advice, and strategic planning to ensure that clients’ interests are protected and their objectives are achieved.',
    serviceBody4: 'Contract drafting and review ensures that agreements are clear, enforceable, and aligned with clients’ interests. This service involves preparing new contracts, analyzing existing ones for potential risks or ambiguities, and advising on necessary revisions to protect clients’ rights and minimize future disputes.',
    contactMeLabel: 'Contact us',
    contactNameLabel: 'Name',
    contactNamePlaceholder: 'John Doe',
    contactEmailLabel: 'Email',
    contactEmailPlaceholder: 'johndoe@gmail.com',
    contactMessageLabel: 'Message',
    contactMessagePlaceholder: 'I contant you, for ....',
}

export const MainPageContentGR = {
    nameLabel: 'Ανδρέας Ν. Δρανδάκης',
    progessionLabel: 'Δικηγόρος | Ειδικός στο Εταιρικό & Πολιτικό Δίκαιο',
    bioHeaderLabel: 'Γειά σας,',
    bioBodyLabel: 'Είμαι ο Ανδρέας, δικηγόρος με άδεια άσκησης επαγγέλματος και πάνω από 10 χρόνια εμπειρίας στο εταιρικό και πολιτικό δίκαιο. Η εξειδίκευσή μου περιλαμβάνει εταιρική διακυβέρνηση, δίκαιο συμβάσεων και επίλυση διαφορών. Δεσμεύομαι να παρέχω στους πελάτες μου την υψηλότερη ποιότητα νομικών υπηρεσιών και υποστήριξης.',
    servicesLabel: 'Υπηρεσίες',
    serviceLabel1: 'Εταιρικό Δίκαιο',
    serviceLabel2: 'Αστικό Δίκαιο',
    serviceLabel3: 'Νομικές Συμβουλευτικές Υπηρεσίες',
    serviceLabel4: 'Σύνταξη και Ανασκόπηση Συμβάσεων',
    serviceBody1: 'Το εταιρικό δίκαιο διέπει τη σύσταση, λειτουργία και διάλυση εταιρειών. Καλύπτει τομείς όπως συγχωνεύσεις και εξαγορές, συμμόρφωση, εταιρική διακυβέρνηση και δικαιώματα μετόχων, διασφαλίζοντας ότι οι επιχειρήσεις λειτουργούν εντός του νομικού πλαισίου και διατηρούν ηθικά πρότυπα.',
    serviceBody2: 'Το αστικό δίκαιο ρυθμίζει τις σχέσεις μεταξύ ιδιωτών ή/και νομικών προσώπων και καλύπτει ζητήματα όπως συμβατικές διαφορές, ιδιοκτησιακά δικαιώματα και αποζημιώσεις. Στόχος του είναι η δίκαιη επίλυση διαφορών μέσω διαπραγμάτευσης, συμβιβασμού ή δικαστικής διαδικασίας.',
    serviceBody3: 'Νομικές συμβουλευτικές υπηρεσίες παρέχουν στους πελάτες ειδική καθοδήγηση σε διάφορα νομικά ζητήματα, βοηθώντας τους να πλοηγηθούν σε περίπλοκους κανονισμούς και να λάβουν ενημερωμένες αποφάσεις. Αυτές οι υπηρεσίες περιλαμβάνουν εκτίμηση κινδύνου, συμβουλές συμμόρφωσης και στρατηγικό σχεδιασμό για να διασφαλιστεί ότι τα συμφέροντα των πελατών προστατεύονται και οι στόχοι τους επιτυγχάνονται.',
    serviceBody4: 'Η σύνταξη και ανασκόπηση συμβάσεων διασφαλίζει ότι οι συμφωνίες είναι σαφείς, εκτελεστές και ευθυγραμμισμένες με τα συμφέροντα των πελατών. Αυτή η υπηρεσία περιλαμβάνει την προετοιμασία νέων συμβολαίων, την ανάλυση υφιστάμενων για πιθανούς κινδύνους ή ασάφειες και τη συμβουλή σχετικά με τις απαραίτητες τροποποιήσεις για την προστασία των δικαιωμάτων των πελατών και τη μείωση μελλοντικών διαφορών.',
    contactMeLabel: 'Επικοινωνήστε μαζί μας',
    contactNameLabel: 'Όνομα',
    contactNamePlaceholder: 'Γιάννης Γιαννάκης',
    contactEmailLabel: 'Ηλεκτρονικό Ταχυδρομείο',
    contactEmailPlaceholder: 'johndoe@gmail.com',
    contactMessageLabel: 'Μήνυμα',
    contactMessagePlaceholder: 'Επικοινωνώ μαζί σας, για ....',
}